### ISSUE TITLE
config command not available in aws elasticache

### ISSUE THREAD

**Issue by jamemackson** [lykmapipo/kue-scheduler#83]
I am recieving this error when attempting to create my queue against an aws elasticache instance:

```
ReplyError: ERR unknown command 'config'
    at new Command (/home/ubuntu/api/node_modules/kue/node_modules/redis/lib/command.js:12:22)
    at RedisClient.config (/home/ubuntu/api/node_modules/kue/node_modules/redis/lib/commands.js:62:47)
    at Queue.enableExpiryNotifications (/home/ubuntu/api/node_modules/kue-scheduler/index.js:370:13)
    at Function.kue.createQueue (/home/ubuntu/api/node_modules/kue-scheduler/index.js:1169:11)
...
```

Is there a known workaround for this?   

I've tracked this back to where it's trying to call this `this._cli.config('SET', 'notify-keyspace-events', 'Ex');` which I can manually set so thinking maybe this can somehow be disabled?  

Any advice is highly appreciated!

**Comment by jamemackson** [comment]
I figured out that an option was added to disable this back in #18 but isn't very well documented (or at least I couldn't find any mention of it.) 

`kue.createQueue({skipConfig: true});` fixed this for me though... (in case this will help someone else in the future.)

**Comment by lykmapipo** [comment]
Hello @jamemackson I will update docs

**Comment by lykmapipo** [comment]
@jamemackson Updated see the docs on options section.

I will appreciate more improvement on the docs and user guides.
