### ISSUE TITLE
Restore failure

### ISSUE THREAD

**Issue by artema** [lykmapipo/kue-scheduler#85]
When setting `restore: true` in the configuration, an error occurs upon startup:

```
TypeError: Cannot read property 'emit' of undefined
    at /Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/index.js:1194:13
    at /Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:3694:9
    at /Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:359:16
    at eachOfArrayLike (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:928:9)
    at eachOf (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:990:5)
    at _parallel (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:3685:5)
    at Object.parallelLimit [as parallel] (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/node_modules/async/dist/async.js:3765:3)
    at Queue.<anonymous> (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/index.js:1483:13)
    at Queue.<anonymous> (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/kue-scheduler/index.js:1420:7)
    at normal_reply (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/redis-parser/lib/parser.js:562:12)
    at Socket.<anonymous> (/Users/Artem/Projects/Digital Touch Systems/dts-api-worker/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by samhunta** [comment]
Is this still an issue?

**Comment by ggutenberg** [comment]
It is definitely still an issue which we encountered a few days ago.  I'm not sure of the exact cause, but it has something to do with Redis throwing an error and kue-scheduler not handling that error correctly.  The PR I just submitted fixes it.
